name: Deploy Vue App to Server

on:
  push:
    branches:
      - main  # or master, depending on your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh root@${{ secrets.SERVER_IP }} << 'EOF'
            cd /var/www/travelninjamainplatform
            git pull origin main
            npm install
            npm run build
            pm2 delete travelninja || true
            pm2 start "serve -s dist -l 5000" --name platform
            pm2 save

